// Auto-generated by Supabase CLI — do not edit manually.
// Run `pnpm types` from root to regenerate.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      instruments: {
        Row: {
          id: number;
          exchange: string;
          exchange_token: number;
          trading_symbol: string;
          groww_symbol: string;
          name: string | null;
          instrument_type: string | null;
          segment: string;
          series: string | null;
          isin: string | null;
          lot_size: number;
          tick_size: number | null;
          is_reserved: boolean;
          buy_allowed: boolean;
          sell_allowed: boolean;
          updated_at: string;
        };
        Insert: {
          id?: number;
          exchange: string;
          exchange_token: number;
          trading_symbol: string;
          groww_symbol: string;
          name?: string | null;
          instrument_type?: string | null;
          segment?: string;
          series?: string | null;
          isin?: string | null;
          lot_size?: number;
          tick_size?: number | null;
          is_reserved?: boolean;
          buy_allowed?: boolean;
          sell_allowed?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: number;
          exchange?: string;
          exchange_token?: number;
          trading_symbol?: string;
          groww_symbol?: string;
          name?: string | null;
          instrument_type?: string | null;
          segment?: string;
          series?: string | null;
          isin?: string | null;
          lot_size?: number;
          tick_size?: number | null;
          is_reserved?: boolean;
          buy_allowed?: boolean;
          sell_allowed?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      watchlists: {
        Row: {
          id: string;
          name: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      watchlist_items: {
        Row: {
          id: string;
          watchlist_id: string;
          trading_symbol: string;
          exchange: string;
          added_at: string;
        };
        Insert: {
          id?: string;
          watchlist_id: string;
          trading_symbol: string;
          exchange?: string;
          added_at?: string;
        };
        Update: {
          id?: string;
          watchlist_id?: string;
          trading_symbol?: string;
          exchange?: string;
          added_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "watchlist_items_watchlist_id_fkey";
            columns: ["watchlist_id"];
            isOneToOne: false;
            referencedRelation: "watchlists";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          id: string;
          groww_order_id: string | null;
          trading_symbol: string;
          exchange: string;
          transaction_type: string;
          order_type: string;
          product: string;
          quantity: number;
          price: number | null;
          trigger_price: number | null;
          status: string | null;
          filled_quantity: number;
          average_fill_price: number | null;
          order_source: string;
          agent_reasoning: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          groww_order_id?: string | null;
          trading_symbol: string;
          exchange?: string;
          transaction_type: string;
          order_type: string;
          product?: string;
          quantity: number;
          price?: number | null;
          trigger_price?: number | null;
          status?: string | null;
          filled_quantity?: number;
          average_fill_price?: number | null;
          order_source?: string;
          agent_reasoning?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          groww_order_id?: string | null;
          trading_symbol?: string;
          exchange?: string;
          transaction_type?: string;
          order_type?: string;
          product?: string;
          quantity?: number;
          price?: number | null;
          trigger_price?: number | null;
          status?: string | null;
          filled_quantity?: number;
          average_fill_price?: number | null;
          order_source?: string;
          agent_reasoning?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      portfolio_snapshots: {
        Row: {
          id: string;
          snapshot_date: string;
          holdings: Json;
          total_invested: number | null;
          total_current: number | null;
          day_pnl: number | null;
          overall_pnl: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          snapshot_date: string;
          holdings: Json;
          total_invested?: number | null;
          total_current?: number | null;
          day_pnl?: number | null;
          overall_pnl?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          snapshot_date?: string;
          holdings?: Json;
          total_invested?: number | null;
          total_current?: number | null;
          day_pnl?: number | null;
          overall_pnl?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          channel: string;
          title: string;
          body: string;
          metadata: Json | null;
          read: boolean;
          sent_at: string;
        };
        Insert: {
          id?: string;
          channel: string;
          title: string;
          body: string;
          metadata?: Json | null;
          read?: boolean;
          sent_at?: string;
        };
        Update: {
          id?: string;
          channel?: string;
          title?: string;
          body?: string;
          metadata?: Json | null;
          read?: boolean;
          sent_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
